import Head from "next/head"
import Image from "next/image"
import { Card, Title, AreaChart } from "@tremor/react"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import Header from "@/components/layout/Header"
import Layout from "@/components/layout/Layout"

const inter = Inter({ subsets: ["latin"] })

const chartdata = [
  {
    date: "Jan 22",
    SemiAnalysis: 2890,
    "The Pragmatic Engineer": 2338,
  },
  {
    date: "Feb 22",
    SemiAnalysis: 2756,
    "The Pragmatic Engineer": 2103,
  },
  {
    date: "Mar 22",
    SemiAnalysis: 3322,
    "The Pragmatic Engineer": 2194,
  },
  {
    date: "Apr 22",
    SemiAnalysis: 3470,
    "The Pragmatic Engineer": 2108,
  },
  {
    date: "May 22",
    SemiAnalysis: 3475,
    "The Pragmatic Engineer": 1812,
  },
  {
    date: "Jun 22",
    SemiAnalysis: 3129,
    "The Pragmatic Engineer": 1726,
  },
]

const valueFormatter = (number: any) =>
  `$ ${new Intl.NumberFormat("us").format(number).toString()}`

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Home Page</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <h1>Home Page</h1>
        <Card>
          <Title>Newsletter revenue over time (USD)</Title>
          <AreaChart
            className='h-72 mt-4'
            data={chartdata}
            index='date'
            categories={["SemiAnalysis", "The Pragmatic Engineer"]}
            colors={["indigo", "cyan"]}
            valueFormatter={valueFormatter}
          />
        </Card>
      </main>
    </Layout>
  )
}
